IP_asset/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  get 'ipcommittee/show'
  post 'ipcommittee/updatestatus'
  get 'ipcommittee/index'
  get '/dashboard', :to => 'ipassets#index'
 get 'ipcommittee/show/:id',to: "ipcommittee#show" , as: "review_ip"
  devise_scope :user do
      get '/logout',  :to => 'devise/sessions#destroy' #, :as => "logout"
      get '/login' , :to => 'devise/sessions#new'  , :as => "login"
      get '/signup' , :to => 'devise/registrations#new'  , :as => "signup"
    end
  
  
  ActiveAdmin.routes(self)
  # get 'welcome/new'
  # post 'welcome/signup'
  resources :ipassets
  authenticated :user do
   root :to => 'ipassets#index', as: :authenticated_root
  end

  devise_scope :user do
      root :to => 'devise/sessions#new' #, :as => "login"
    end
 
  #get "new" => 'ipasset#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

IP_asset/app/models/ipasset.rb
class Ipasset < ApplicationRecord

	
mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
has_many :stakeholders, foreign_key: 'ipassetid', inverse_of: :ipasset
has_many :users , through: :stakeholders
accepts_nested_attributes_for :stakeholders
accepts_nested_attributes_for :users

end

IP_asset/app/controllers/ipassets_controller.rb
class IpassetsController < ApplicationController
  before_action :login_required

  def index
  @ipasset = current_user.ipassets.all
  end


  def show
    @ipasset = Ipasset.find(params[:id])
  end


  def new 
    @ipasset = Ipasset.new
    @ipasset.stakeholders.build(stakeholderid: current_user.id)
  end

  def edit
    @ipasset = Ipasset.find(params[:id])
  end

  def create
  	@ipasset = Ipasset.new(ipasset_params)
  	@ipasset.save
  	redirect_to @ipasset
  end

  def update
    @ipasset = Ipasset.find(params[:id])
    if @ipasset.update(ipasset_params)
      redirect_to @ipasset
    else
      render 'edit'
    end
  end

  private

  def ipasset_params
    params.require(:ipasset).permit(:title, :description, :attachment, :filename , stakeholders_attributes: [:stakeholderid, :stakespercent])
  end
end

IP_asset/app/helpers/ipassets_helper.rb
module IpassetsHelper
end

IP_asset/app/views/ipassets/_stakeholder_fields.html.erb
<div class="nested-fields">
      <%= f.label :stakeholderid %><br>
      <%= f.text_field :stakeholderid %><br>


      <%= f.label :stakespercent %><br>
      <%= f.text_field :stakespercent %><br>

  
 </div>

IP_asset/app/views/ipassets/edit.html.erb
 




<!DOCTYPE html>
    <!--[if IE 9 ]><html class="ie9"><![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Material Admin</title>
    
        <!-- Vendor CSS -->
        <link href="/material/vendors/bower_components/animate.css/animate.min.css" rel="stylesheet">
        <link href="/material/vendors/bower_components/bootstrap-sweetalert/lib/sweet-alert.css" rel="stylesheet">
        <link href="/material/vendors/bower_components/material-design-iconic-font/dist/css/material-design-iconic-font.min.css" rel="stylesheet">
        <link href="/material/vendors/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css" rel="stylesheet">        
            
        <!-- CSS -->
        <link href="/material/css/app.min.1.css" rel="stylesheet">
        <link href="/material/css/app.min.2.css" rel="stylesheet">
    </head>
    
    <body>
        <header id="header" class="clearfix" data-current-skin="blue">
            <ul class="header-inner">
                <li id="menu-trigger" data-trigger="#sidebar">
                    <div class="line-wrap">
                        <div class="line top"></div>
                        <div class="line center"></div>
                        <div class="line bottom"></div>
                    </div>
                </li>

                <li class="logo hidden-xs">
                    <a href="index.html">Material Admin</a>
                </li>

                <li class="pull-right">
                    <ul class="top-menu">
                        <li id="toggle-width">
                            <div class="toggle-switch">
                                <input id="tw-switch" type="checkbox" hidden="hidden">
                                <label for="tw-switch" class="ts-helper"></label>
                            </div>
                        </li>

                        <li id="top-search">
                            <a href=""><i class="tm-icon zmdi zmdi-search"></i></a>
                        </li>

                        
            


            <!-- Top Search Content -->
            <div id="top-search-wrap">
                <div class="tsw-inner">
                    <i id="top-search-close" class="zmdi zmdi-arrow-left"></i>
                    <input type="text">
                </div>
            </div>
        </header>
        
        <section id="main">
            <aside id="sidebar" class="sidebar c-overflow">
                <div class="profile-menu">
                    <a href="">
                        <div class="profile-pic">
                            <img src="/material/img/profile-pics/1.jpg" alt="">
                        </div>

                        <div class="profile-info">
                            Shreyak Upadhyay

                            <i class="zmdi zmdi-caret-down"></i>
                        </div>
                    </a>

                    <ul class="main-menu">
                        <li>
                            <a href="profile-about.html"><i class="zmdi zmdi-account"></i> View Profile</a>
                        </li>
                        <li>
                            <a href=""><i class="zmdi zmdi-input-antenna"></i> Privacy Settings</a>
                        </li>
                        <li>
                            <a href=""><i class="zmdi zmdi-settings"></i> Settings</a>
                        </li>
                        <li>
                            <a href=""><i class="zmdi zmdi-time-restore"></i> Logout</a>
                        </li>
                    </ul>
                </div>

                <ul class="main-menu">
                    <li><a href="index.html"><i class="zmdi zmdi-home"></i> Home</a></li>
                    
                </ul>
            </aside>

            
        
            <section id="content">
                <div class="container">
                    <div class="block-header">
                        <h2>Form Examples</h2>
                    
                        <ul class="actions">
                            <li>
                                <a href="">
                                    <i class="zmdi zmdi-trending-up"></i>
                                </a>
                            </li>
                            <li>
                                <a href="">
                                    <i class="zmdi zmdi-check-all"></i>
                                </a>
                            </li>
                            <li class="dropdown">
                                <a href="" data-toggle="dropdown">
                                    <i class="zmdi zmdi-more-vert"></i>
                                </a>
                    
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li>
                                        <a href="">Refresh</a>
                                    </li>
                                    <li>
                                        <a href="">Manage Widgets</a>
                                    </li>
                                    <li>
                                        <a href="">Widgets Settings</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                
                    <div class="card">
                        <div class="card-header">
                            <h2>Edit IPassets <small>Individual form controls automatically receive some global styling. All textual 'input', 'textarea', and 'select' elements with .form-control are set to width: 100%; by default. Wrap labels and controls in .form-group for optimum spacing.
</small></h2>
                        </div>
                        
                        <div class="card-body card-padding">
                            
                              <%= form_for :ipasset, url: ipasset_path(@ipasset), method: :patch do |f| %>
                                <% if @ipasset.errors.any? %>
                                  <div id="error_explanation">
                                    <h2>
                                      <%= pluralize(@ipasset.errors.count, "error") %> prohibited
                                      this ipasset from being saved:
                                    </h2>
                                    <ul>
                                      <% @ipasset.errors.full_messages.each do |msg| %>
                                        <li><%= msg %></li>
                                      <% end %>
                                    </ul>
                                  </div>
                                <% end %>
                                <span class="input-group-addon"></span>
                                <div class="fg-line" type="text" class="form-control" placeholder="Password"> 
                                    <%= label_tag("Title") %> 
                                    <%= f.text_field :title, autocomplete: "off", class: 'fg-line form-group form-control' %>
                                </div>
                                
                                <span class="input-group-addon"></span>
                                <div class="fg-line" type="text" class="form-control" placeholder="Password"> 
                                    <%= label_tag("Description") %>
                                    <%= f.text_area :description, autocomplete: "off", class: 'form-control' %>
                                </div>

                                <span class="input-group-addon"></span>
                                <div class="fg-line" type="text" class="form-control" placeholder="Password"> 
                                    <%= label_tag("Binary Data") %> 
                                    <%= f.file_field :binary_data, autocomplete: "off", class: 'form-control' %>
                                </div>

                                <span class="input-group-addon"></span>
                                <div class="fg-line" type="text" class="form-control" placeholder="Password"> 
                                    <%= label_tag("Filename") %>
                                    <%= f.text_field :filename, autocomplete: "off", class: 'form-control' %>
                                </div>

                                
                    
                                <!--</div>                               


                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" value="">
                                        <i class="input-helper"></i>
                                        Don't forget to check me out
                                    </label>
                                </div>
                                
                                <!--<button type="submit" class="btn btn-primary btn-sm m-t-10">Submit</button>-->
                                <p>
                                    <%= f.submit 'Save Ipasset', :class => 'btn' %>
                                </p>
                                <% end %>
                                <%= link_to 'Back', ipassets_path, :class => 'btn' %>
  
                        </div>
                    </div>                 
                    
                    
                </div>
            </section>
        </section>
        
        <footer id="footer">
            Copyright &copy; 2015 Material Admin
            
            <ul class="f-menu">
                <li><a href="">Home</a></li>
                <li><a href="">Dashboard</a></li>
                <li><a href="">Reports</a></li>
                <li><a href="">Support</a></li>
                <li><a href="">Contact</a></li>
            </ul>
        </footer>

        <!-- Page Loader -->
        <div class="page-loader">
            <div class="preloader pls-blue">
                <svg class="pl-circular" viewBox="25 25 50 50">
                    <circle class="plc-path" cx="50" cy="50" r="20" />
                </svg>

                <p>Please wait...</p>
            </div>
        </div>

        <!-- Older IE warning message -->
        <!--[if lt IE 9]>
            <div class="ie-warning">
                <h1 class="c-white">Warning!!</h1>
                <p>You are using an outdated version of Internet Explorer, please upgrade <br/>to any of the following web browsers to access this website.</p>
                <div class="iew-container">
                    <ul class="iew-download">
                        <li>
                            <a href="http://www.google.com/chrome/">
                                <img src="img/browsers/chrome.png" alt="">
                                <div>Chrome</div>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.mozilla.org/en-US/firefox/new/">
                                <img src="img/browsers/firefox.png" alt="">
                                <div>Firefox</div>
                            </a>
                        </li>
                        <li>
                            <a href="http://www.opera.com">
                                <img src="img/browsers/opera.png" alt="">
                                <div>Opera</div>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.apple.com/safari/">
                                <img src="img/browsers/safari.png" alt="">
                                <div>Safari</div>
                            </a>
                        </li>
                        <li>
                            <a href="http://windows.microsoft.com/en-us/internet-explorer/download-ie">
                                <img src="img/browsers/ie.png" alt="">
                                <div>IE (New)</div>
                            </a>
                        </li>
                    </ul>
                </div>
                <p>Sorry for the inconvenience!</p>
            </div>   
        <![endif]-->
    
        <!-- Javascript Libraries -->
        <script src="/material/vendors/bower_components/jquery/dist/jquery.min.js"></script>
        <script src="/material/vendors/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
        
                <script src="/material/vendors/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
        <script src="/material/vendors/bower_components/Waves/dist/waves.min.js"></script>
        <script src="/material/vendors/bootstrap-growl/bootstrap-growl.min.js"></script>
        <script src="/material/vendors/bower_components/bootstrap-sweetalert/lib/sweet-alert.min.js"></script>
        <script src="/material/vendors/bower_components/autosize/dist/autosize.min.js"></script>
        
        <!-- Placeholder for IE9 -->
        <!--[if IE 9 ]>
            <script src="/material/vendors/bower_components/jquery-placeholder/jquery.placeholder.min.js"></script>
        <![endif]-->
        
        <script src="/material/js/functions.js"></script>
        <script src="/material/js/demo.js"></script>
    
    
    </body>
</html>

IP_asset/app/views/ipassets/index.html.erb
<!DOCTYPE html>
<!--[if IE 9 ]><html class="ie9"><![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Material Admin</title>
        
        <!-- Vendor CSS -->
        <link href="/material/vendors/bower_components/animate.css/animate.min.css" rel="stylesheet">
        <link href="/material/vendors/bower_components/bootstrap-sweetalert/lib/sweet-alert.css" rel="stylesheet">
        <link href="/material/vendors/bower_components/material-design-iconic-font/dist/css/material-design-iconic-font.min.css" rel="stylesheet">
        <link href="/material/vendors/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css" rel="stylesheet">
        <link href="/material/vendors/bootgrid/jquery.bootgrid.min.css" rel="stylesheet">


        <!-- CSS -->
        <link href="/material/css/app.min.1.css" rel="stylesheet">
        <link href="/material/css/app.min.2.css" rel="stylesheet">
    </head>
    <body>
        <header id="header" class="clearfix" data-current-skin="blue">
            <ul class="header-inner">
                <li id="menu-trigger" data-trigger="#sidebar">
                    <div class="line-wrap">
                        <div class="line top"></div>
                        <div class="line center"></div>
                        <div class="line bottom"></div>
                    </div>
                </li>

                <li class="logo hidden-xs">
                    <a href="index.html">Material Admin</a>
                </li>

                
            </ul>


            <!-- Top Search Content -->
            <div id="top-search-wrap">
                <div class="tsw-inner">
                    <i id="top-search-close" class="zmdi zmdi-arrow-left"></i>
                    <input type="text">
                </div>
            </div>
        </header>
        
        <section id="main">
            <aside id="sidebar" class="sidebar c-overflow">
                <div class="profile-menu">
                    <a href="">
                        <div class="profile-pic">
                            <img src="/material/img/profile-pics/1.jpg" alt="">
                        </div>

                        <div class="profile-info">
                            Shreyak Upadhyay

                            <i class="zmdi zmdi-caret-down"></i>
                        </div>
                    </a>

                    <ul class="main-menu">
                        <li>
                            <a href="profile-about.html"><i class="zmdi zmdi-account"></i> View Profile</a>
                        </li>
                        <li>
                            <a href=""><i class="zmdi zmdi-input-antenna"></i> Privacy Settings</a>
                        </li>
                        <li>
                            <a href=""><i class="zmdi zmdi-settings"></i> Settings</a>
                        </li>
                        <li>
                            <a href=""><i class="zmdi zmdi-time-restore"></i> Logout</a>
                        </li>
                    </ul>
                </div>

                <ul class="main-menu">
                    <li><a href="index.html"><i class="zmdi zmdi-home"></i> Home</a></li>
                    
                </ul>
            </aside>
           
            

            <section id="content">
                <div class="container">
                    <div class="block-header">
                        <h2>Data Table</h2>
                        
                        <ul class="actions">
                            <li>
                                <a href="">
                                    <i class="zmdi zmdi-trending-up"></i>
                                </a>
                            </li>
                            <li>
                                <a href="">
                                    <i class="zmdi zmdi-check-all"></i>
                                </a>
                            </li>
                            <li class="dropdown">
                                <a href="" data-toggle="dropdown">
                                    <i class="zmdi zmdi-more-vert"></i>
                                </a>
                                
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li>
                                        <a href="">Refresh</a>
                                    </li>
                                    <li>
                                        <a href="">Manage Widgets</a>
                                    </li>
                                    <li>
                                        <a href="">Widgets Settings</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                                    
                    
                    
                    <div class="card">
                        <div class="card-header">
                            <h2>Listing IP Assets <small>Ensure that the data attribute [data-identifier="true"] is set on one column header.</small></h2>
                        </div>
                        
                        <table id="data-table-command" class="table table-striped table-vmiddle">
                            <thead>
                                <tr>
                                    <th data-column-id="id" data-type="numeric">Title</th>
                                    <th data-column-id="sender">Description</th>
                                    <th data-column-id="received" data-order="desc">Filename</th>
                                    <th data-column-id="commands" data-formatter="commands" data-sortable="false">Commands</th>
                                </tr>
                            </thead>
                             

                            <tbody>
                               
                                         
                                <% @ipasset.each do |ipasset| %>
                                  <tr>
                                    <td><%= ipasset.title %></td>
                                    <td><%= ipasset.description %></td>
                                    <td><%= ipasset.filename %></td>
                                    <td><a href="<%= ipasset_path(ipasset)%>"class="btn btn-icon command-page waves-effect waves-circle"><span class="zmdi zmdi-view-agenda"></span></button>
                                    <a href="<%= edit_ipasset_path(ipasset)%>"class="btn btn-icon command-edit waves-effect waves-circle"><span class="zmdi zmdi-edit"></span></button></td>
                                  </tr>
                                <% end %>

                            </tbody>

                        </table>
                    </div>
                </div>
            </section>
        </section>
        
        <footer id="footer">
            Copyright &copy; 2015 Material Admin
            
            <ul class="f-menu">
                <li><a href="">Home</a></li>
                <li><a href="">Dashboard</a></li>
                <li><a href="">Reports</a></li>
                <li><a href="">Support</a></li>
                <li><a href="">Contact</a></li>
            </ul>
        </footer>

        <!-- Page Loader -->
        <div class="page-loader">
            <div class="preloader pls-blue">
                <svg class="pl-circular" viewBox="25 25 50 50">
                    <circle class="plc-path" cx="50" cy="50" r="20" />
                </svg>

                <p>Please wait...</p>
            </div>
        </div>

        <!-- Older IE warning message -->
        <!--[if lt IE 9]>
            <div class="ie-warning">
                <h1 class="c-white">Warning!!</h1>
                <p>You are using an outdated version of Internet Explorer, please upgrade <br/>to any of the following web browsers to access this website.</p>
                <div class="iew-container">
                    <ul class="iew-download">
                        <li>
                            <a href="http://www.google.com/chrome/">
                                <img src="img/browsers/chrome.png" alt="">
                                <div>Chrome</div>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.mozilla.org/en-US/firefox/new/">
                                <img src="img/browsers/firefox.png" alt="">
                                <div>Firefox</div>
                            </a>
                        </li>
                        <li>
                            <a href="http://www.opera.com">
                                <img src="img/browsers/opera.png" alt="">
                                <div>Opera</div>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.apple.com/safari/">
                                <img src="img/browsers/safari.png" alt="">
                                <div>Safari</div>
                            </a>
                        </li>
                        <li>
                            <a href="http://windows.microsoft.com/en-us/internet-explorer/download-ie">
                                <img src="img/browsers/ie.png" alt="">
                                <div>IE (New)</div>
                            </a>
                        </li>
                    </ul>
                </div>
                <p>Sorry for the inconvenience!</p>
            </div>   
        <![endif]-->

        <!-- Javascript Libraries -->
        <script src="/material/vendors/bower_components/jquery/dist/jquery.min.js"></script>
        <script src="/material/vendors/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
        
        <script src="/material/vendors/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
        <script src="/material/vendors/bower_components/Waves/dist/waves.min.js"></script>
        <script src="/material/vendors/bootstrap-growl/bootstrap-growl.min.js"></script>
        <script src="/material/vendors/bower_components/bootstrap-sweetalert/lib/sweet-alert.min.js"></script>  
        <script src="/material/vendors/bootgrid/jquery.bootgrid.updated.min.js"></script>
        
        <!-- Placeholder for IE9 -->
        <!--[if IE 9 ]>
            <script src="/material/vendors/bower_components/jquery-placeholder/jquery.placeholder.min.js"></script>
        <![endif]-->
        
        <script src="/material/js/functions.js"></script>
        <script src="/material/js/demo.js"></script>

        <!-- Data Table -->
        <script type="text/javascript">
            $(document).ready(function(){
                //Basic Example
                $("#data-table-basic").bootgrid({
                    css: {
                        icon: 'zmdi icon',
                        iconColumns: 'zmdi-view-module',
                        iconDown: 'zmdi-expand-more',
                        iconRefresh: 'zmdi-refresh',
                        iconUp: 'zmdi-expand-less'
                    },
                });
                
                //Selection
                $("#data-table-selection").bootgrid({
                    css: {
                        icon: 'zmdi icon',
                        iconColumns: 'zmdi-view-module',
                        iconDown: 'zmdi-expand-more',
                        iconRefresh: 'zmdi-refresh',
                        iconUp: 'zmdi-expand-less'
                    },
                    selection: true,
                    multiSelect: true,
                    rowSelect: true,
                    keepSelection: true
                });
                
                //Command Buttons
                // $("#data-table-command").bootgrid({
                //     css: {
                //         icon: 'zmdi icon',
                //         iconColumns: 'zmdi-view-module',
                //         iconDown: 'zmdi-expand-more',
                //         iconRefresh: 'zmdi-refresh',
                //         iconUp: 'zmdi-expand-less'
                //     },
                //     formatters: {
                //         "commands": function(column, row) {
                //             return "<button type=\"button\" class=\"btn btn-icon command-edit waves-effect waves-circle\" data-row-id=\"" + row.id + "\"><span class=\"zmdi zmdi-edit\"></span></button> " + 
                //                 "<button type=\"button\" class=\"btn btn-icon command-delete waves-effect waves-circle\" data-row-id=\"" + row.id + "\"><span class=\"zmdi zmdi-delete\"></span></button>";
                //         }
                //     }
                // });
            });
        </script>
    </body>
  </html>